"""Packaging Service — FR5 in-app view assembly and PDF export.

- FR5.1/FR5.4  ``build_in_app_view``: summary + ranked, annotated item list
               (deep links ``/documents/{document_id}``) + appendix with
               analysis tables. Charts are built ONLY from computed analysis
               outputs (Vega-Lite specs via the smart_folder chart_generator);
               nothing is ever drawn from raw LLM prose.
- FR5.6        ``export_pdf``: reportlab export following the collections.py
               pattern — header with request params summary, generation
               timestamp (UTC) and data-as-of date; disclosures are listed
               BEFORE the item list; every page footer reads
               "Generated by SOWKNOW Collection · <timestamp> · data as of <date>".
- FR5.2        ``export_docx``: python-docx Word export with the same
               content blocks as the PDF (header/footer info, disclosures,
               summary, item list, appendix tables).
- FR5.3        Citation links are internal URIs (``/documents/{id}``); the
               frontend re-checks permission at navigation. The deliverable
               JSON records this as ``links_permission_bound: true``.
"""

import io
import logging
import re
from datetime import datetime, timezone
from typing import Any

from app.services.collection_orchestrator.sanitise import sanitise_item, sanitise_text, sanitise_view
from app.services.collection_orchestrator.summary_generator import SECTIONS
from app.services.smart_folder.tools.chart_generator import chart_generator

logger = logging.getLogger(__name__)

BRAND_BLUE = "#1E40AF"
BRAND_GREY = "#6B7280"


# ---------------------------------------------------------------------------
# FR5.1 / FR5.4 — in-app view
# ---------------------------------------------------------------------------

def _item_view(item: dict[str, Any]) -> dict[str, Any]:
    document_id = item.get("document_id")
    return {
        "id": str(item.get("id")) if item.get("id") else None,
        "document_id": str(document_id) if document_id else None,
        "title": item.get("title"),
        "annotation": item.get("annotation") or item.get("annotation_text"),
        "category_tags": item.get("category_tags") or [],
        "date": _iso(item.get("item_date") or item.get("date")),
        "source": item.get("source"),
        "author": item.get("author"),
        "snippet": item.get("snippet"),
        "rank_position": item.get("rank_position"),
        "relevance_score": item.get("relevance_score"),
        "status": item.get("status") or "ok",
        "page_number": item.get("page_number"),
        # FR5.3 — internal deep link; permission re-checked at navigation.
        "link": f"/documents/{document_id}" if document_id else None,
        "related_items": [
            {
                "id": str(dup.get("id")) if dup.get("id") else None,
                "document_id": str(dup.get("document_id")) if dup.get("document_id") else None,
                "title": dup.get("title"),
                "link": f"/documents/{dup.get('document_id')}" if dup.get("document_id") else None,
            }
            for dup in item.get("related_items") or []
        ],
    }


def _iso(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.isoformat()
    return str(value)


def _analysis_appendix(analyses: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Tables from computed outputs; charts only from computed series."""
    appendix: list[dict[str, Any]] = []
    for analysis in analyses or []:
        analysis_type = analysis.get("analysis_type")
        output = analysis.get("output") or {}
        entry: dict[str, Any] = {
            "analysis_type": analysis_type,
            "tables": [],
            "charts": [],
            "messages": [],
        }

        if analysis_type == "descriptive":
            rows = [
                {
                    "metric": m.get("metric"),
                    "unit": m.get("unit"),
                    "count": m.get("count"),
                    "total": m.get("total"),
                    "mean": m.get("mean"),
                    "min": m.get("min"),
                    "max": m.get("max"),
                }
                for m in output.get("metrics") or []
            ]
            if rows:
                entry["tables"].append({
                    "title": "Descriptive statistics",
                    "columns": ["metric", "unit", "count", "total", "mean", "min", "max"],
                    "rows": rows,
                })

        elif analysis_type == "trend":
            table_rows = []
            for trend in output.get("trends") or []:
                if not trend.get("sufficient_data"):
                    entry["messages"].append(
                        f"{trend.get('metric')}: {trend.get('message', 'insufficient data')}"
                    )
                    continue
                table_rows.append({
                    "metric": trend.get("metric"),
                    "unit": trend.get("unit"),
                    "direction": trend.get("direction"),
                    "slope": trend.get("slope"),
                })
                points = [
                    {"period": str(p.get("period")), "value": p.get("value")}
                    for p in trend.get("points") or []
                    if p.get("value") is not None
                ]
                if len(points) >= 2:
                    # Chart built strictly from computed trend points.
                    entry["charts"].append(chart_generator.line_chart(
                        points,
                        x_field="period",
                        y_field="value",
                        title=f"{trend.get('metric')} trend",
                    ))
            if table_rows:
                entry["tables"].append({
                    "title": "Trends",
                    "columns": ["metric", "unit", "direction", "slope"],
                    "rows": table_rows,
                })

        elif analysis_type == "anomaly":
            table_rows = []
            for metric in output.get("metrics") or []:
                if not metric.get("sufficient_data"):
                    entry["messages"].append(
                        f"{metric.get('metric')}: {metric.get('message', 'insufficient data')}"
                    )
                    continue
                for anomaly in metric.get("anomalies") or []:
                    table_rows.append({
                        "metric": metric.get("metric"),
                        "value": anomaly.get("value"),
                        "date": anomaly.get("date"),
                        "rules": ", ".join(anomaly.get("rules") or []),
                        "z_score": anomaly.get("z_score"),
                    })
            if table_rows:
                entry["tables"].append({
                    "title": "Anomalies",
                    "columns": ["metric", "value", "date", "rules", "z_score"],
                    "rows": table_rows,
                })

        elif analysis_type == "comparison":
            if not output.get("sufficient_data"):
                entry["messages"].append(output.get("message", "insufficient data"))
            for comparison in output.get("comparisons") or []:
                title = comparison.get("family") or f"Comparison ({comparison.get('unit') or 'no unit'})"
                entry["tables"].append({
                    "title": f"Ranking — {title}",
                    "columns": ["rank", "label", "count", "total", "mean"],
                    "rows": comparison.get("ranking") or [],
                })
                pairwise = comparison.get("pairwise") or []
                if pairwise:
                    entry["tables"].append({
                        "title": f"Pairwise differences — {title}",
                        "columns": ["a", "b", "total_difference", "mean_difference"],
                        "rows": pairwise,
                    })

        elif analysis_type == "correlation":
            if not output.get("sufficient_data"):
                message = output.get("message", "insufficient data")
                best = output.get("best_observed")
                if best:
                    message += (
                        f" (best observed: {best.get('metric_a')} vs "
                        f"{best.get('metric_b')}, r = {best.get('r')}, "
                        f"n = {best.get('n')})"
                    )
                entry["messages"].append(message)
            correlations = output.get("correlations") or []
            if correlations:
                entry["tables"].append({
                    "title": "Correlations (association, not causation)",
                    "columns": ["metric_a", "metric_b", "n", "r", "p_value"],
                    "rows": correlations,
                })

        elif output.get("message"):
            entry["messages"].append(output["message"])

        appendix.append(entry)
    return appendix


def build_in_app_view(
    deliverable: Any,
    items_with_annotations: list[dict[str, Any]],
    analyses: list[dict[str, Any]],
) -> dict[str, Any]:
    """FR5.1: summary + ranked item list + appendix, all permission-bound.

    FR7.2: every user-content field (summary, titles, snippets,
    annotations) is sanitised before rendering — filenames and chunk text
    are attacker-controllable.
    """
    sorted_items = sorted(
        items_with_annotations,
        key=lambda it: (it.get("rank_position") is None, it.get("rank_position") or 0),
    )
    dates = [
        _iso(it.get("item_date") or it.get("date"))
        for it in items_with_annotations
    ]
    dates = [d for d in dates if d]
    return {
        "deliverable_id": str(getattr(deliverable, "id", "")),
        "request_id": str(getattr(deliverable, "request_id", "")),
        "version": getattr(deliverable, "version", 1),
        "summary_md": sanitise_text(getattr(deliverable, "summary_md", None)),
        "items": [sanitise_item(_item_view(it)) for it in sorted_items],
        "appendix": {
            **(getattr(deliverable, "appendix", None) or {}),
            "analyses_rendered": _analysis_appendix(analyses),
        },
        "disclosures": getattr(deliverable, "disclosures", None) or [],
        "data_as_of": max(dates) if dates else None,
        "generated_at": _iso(getattr(deliverable, "created_at", None)),
        # FR5.3 — every link is an internal URI; the frontend re-checks
        # permission when the user navigates.
        "links_permission_bound": True,
    }


# ---------------------------------------------------------------------------
# FR5.6 — PDF export
# ---------------------------------------------------------------------------

_MD_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
_MD_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")
_MD_ITALIC_RE = re.compile(r"(?<!\w)\*(.+?)\*(?!\w)")
_MD_BULLET_RE = re.compile(r"^\s*[-*+]\s+")


def _md_to_flowables(md: str, styles: dict[str, Any]) -> list[Any]:
    """Minimal markdown → platypus flowables (headings, bullets, paragraphs)."""
    from reportlab.platypus import Paragraph, Spacer
    from reportlab.lib.units import inch

    flowables: list[Any] = []
    for line in (md or "").splitlines():
        stripped = line.strip()
        if not stripped or stripped == "---":
            continue
        heading = _MD_HEADING_RE.match(stripped)
        text = _MD_BOLD_RE.sub(r"<b>\1</b>", stripped)
        text = _MD_ITALIC_RE.sub(r"<i>\1</i>", text)
        if heading:
            flowables.append(Paragraph(text, styles["heading"]))
        elif _MD_BULLET_RE.match(stripped):
            flowables.append(Paragraph("• " + _MD_BULLET_RE.sub("", text), styles["normal"]))
        else:
            flowables.append(Paragraph(text, styles["normal"]))
        flowables.append(Spacer(1, 0.04 * inch))
    return flowables


def _disclosure_text(disclosure: dict[str, Any]) -> str:
    dtype = disclosure.get("type", "disclosure")
    if dtype == "truncation":
        return (
            f"Truncation: {disclosure.get('items_processed')} item(s) processed"
            + (" (result set truncated at the retrieval cap)" if disclosure.get("truncated") else "")
            + f". Ranking rule: {disclosure.get('ranking_rule')}."
        )
    if dtype == "degraded_sources":
        return (
            f"Degraded sources: {len(disclosure.get('failed_queries') or [])} "
            "search call(s) failed permanently; results are partial."
        )
    if dtype == "removed_claims":
        return (
            f"Removed claims: {disclosure.get('count')} statement(s) stripped "
            "from the summary during grounding validation."
        )
    if dtype == "conflicts":
        return (
            f"Conflicts: {disclosure.get('count')} conflicting fact value(s) "
            "resolved by source precedence (see appendix)."
        )
    if dtype == "zero_results":
        return "Zero results: no items matched the confirmed parameters."
    if dtype == "acl_trimming":
        if disclosure.get("shown") and disclosure.get("trimmed_count") is not None:
            return (
                f"Access control: {disclosure.get('trimmed_count')} matching "
                "document(s) excluded by permission trimming."
            )
        return (
            "Access control: some matching documents were excluded by "
            "permission trimming."
        )
    if dtype == "no_summary":
        return f"Summary: {disclosure.get('message', 'insufficient data for summary')}."
    return str(disclosure.get("message") or dtype)


def export_pdf(deliverable: Any, view: dict[str, Any]) -> bytes:
    """FR5.6: PDF bytes for a deliverable view (reportlab, collections.py pattern).

    FR7.2: the view is sanitised first (idempotent — a view from
    ``build_in_app_view`` is already clean) so a raw ``<`` in a title or
    the summary can never reach reportlab's mini-HTML parser as markup.
    """
    view = sanitise_view(view)
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        HRFlowable,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    generated_at = datetime.now(timezone.utc)
    generated_str = generated_at.strftime("%Y-%m-%d %H:%M UTC")
    data_as_of = (view.get("data_as_of") or "unknown")[:10]

    buffer = io.BytesIO()

    footer_text = f"Generated by SOWKNOW Collection · {generated_str} · data as of {data_as_of}"

    def _add_footer(canv, doc):
        canv.saveState()
        canv.setFont("Helvetica", 8)
        canv.setFillColor(colors.HexColor(BRAND_GREY))
        page_width = letter[0]
        footer_y = 0.3 * inch
        canv.drawString(0.75 * inch, footer_y, footer_text)
        canv.drawRightString(page_width - 0.75 * inch, footer_y, f"Page {doc.page}")
        canv.restoreState()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )
    base = getSampleStyleSheet()
    brand_blue = colors.HexColor(BRAND_BLUE)
    styles = {
        "title": ParagraphStyle("COTitle", parent=base["Heading1"], fontSize=18, textColor=brand_blue, spaceAfter=6),
        "subtitle": ParagraphStyle("COSubtitle", parent=base["Normal"], fontSize=10, textColor=colors.HexColor(BRAND_GREY), spaceAfter=4),
        "heading": ParagraphStyle("COHeading", parent=base["Heading2"], fontSize=13, textColor=brand_blue, spaceBefore=12, spaceAfter=6),
        "normal": base["Normal"],
        "small": ParagraphStyle("COSmall", parent=base["Normal"], fontSize=9, textColor=colors.HexColor(BRAND_GREY)),
    }

    story: list[Any] = []

    # ── Header: request params summary, timestamps (FR5.6) ───────────────
    story.append(Paragraph("SOWKNOW Collection Deliverable", styles["title"]))
    story.append(Paragraph(
        f"Generated {generated_str} &nbsp;·&nbsp; Data as of {data_as_of}",
        styles["subtitle"],
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=brand_blue, spaceAfter=10))

    appendix = view.get("appendix") or {}
    params_lines = []
    request = appendix.get("request_params")
    if request:
        params_lines.append(f"<b>Request:</b> {request}")
    story.append(Paragraph(
        f"<b>Deliverable v{view.get('version', 1)}</b> &nbsp;·&nbsp; "
        f"{len(view.get('items') or [])} item(s) &nbsp;·&nbsp; "
        "Links are permission-bound (re-checked at navigation).",
        styles["normal"],
    ))
    for line in params_lines:
        story.append(Paragraph(line, styles["normal"]))
    story.append(Spacer(1, 0.15 * inch))

    # ── Disclosures BEFORE the item list (FR5.6) ─────────────────────────
    disclosures = view.get("disclosures") or []
    if disclosures:
        story.append(Paragraph("Disclosures", styles["heading"]))
        for disclosure in disclosures:
            story.append(Paragraph("• " + _disclosure_text(disclosure), styles["normal"]))
        story.append(Spacer(1, 0.1 * inch))

    # ── Summary ──────────────────────────────────────────────────────────
    if view.get("summary_md"):
        story.append(Paragraph("Summary", styles["heading"]))
        story.extend(_md_to_flowables(view["summary_md"], styles))
        story.append(Spacer(1, 0.1 * inch))

    # ── Item list ────────────────────────────────────────────────────────
    items = view.get("items") or []
    if items:
        story.append(Paragraph("Source Items", styles["heading"]))
        table_data = [["#", "Title", "Date", "Annotation"]]
        for item in items:
            title = (item.get("title") or "untitled")[:60]
            date = (item.get("date") or "—")[:10]
            annotation = (item.get("annotation") or "")[:180]
            table_data.append([
                str(item.get("rank_position") or "—"),
                title,
                date,
                annotation,
            ])
        table = Table(
            table_data,
            colWidths=[0.4 * inch, 2.2 * inch, 0.9 * inch, 3.5 * inch],
            repeatRows=1,
        )
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), brand_blue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F3F4F6")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(table)

    # ── Appendix: analysis tables (charts stay in the in-app view) ───────
    rendered = appendix.get("analyses_rendered") or []
    if rendered:
        story.append(Paragraph("Appendix — Computed Analyses", styles["heading"]))
        for entry in rendered:
            story.append(Paragraph(
                f"<b>{entry.get('analysis_type')}</b>", styles["normal"]
            ))
            for message in entry.get("messages") or []:
                story.append(Paragraph(f"• {message}", styles["small"]))
            for table_spec in entry.get("tables") or []:
                columns = table_spec.get("columns") or []
                rows = [
                    [str(row.get(col, "—")) for col in columns]
                    for row in table_spec.get("rows") or []
                ]
                if not rows:
                    continue
                a_table = Table([columns, *rows], repeatRows=1)
                a_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E5E7EB")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]))
                story.append(Spacer(1, 0.05 * inch))
                story.append(a_table)
            story.append(Spacer(1, 0.08 * inch))

    doc.build(story, onFirstPage=_add_footer, onLaterPages=_add_footer)
    return buffer.getvalue()


# ---------------------------------------------------------------------------
# FR5.2 — Word export (same content as the PDF)
# ---------------------------------------------------------------------------

def _md_to_blocks(md: str) -> list[tuple[str, str]]:
    """Minimal markdown → (kind, text) blocks; inline markers stripped."""
    blocks: list[tuple[str, str]] = []
    for line in (md or "").splitlines():
        stripped = line.strip()
        if not stripped or stripped == "---":
            continue
        heading = _MD_HEADING_RE.match(stripped)
        text = _MD_BOLD_RE.sub(r"\1", stripped)
        text = _MD_ITALIC_RE.sub(r"\1", text)
        if heading:
            blocks.append(("heading", text))
        elif _MD_BULLET_RE.match(stripped):
            blocks.append(("bullet", _MD_BULLET_RE.sub("", text)))
        else:
            blocks.append(("para", text))
    return blocks


def export_docx(deliverable: Any, view: dict[str, Any]) -> bytes:
    """FR5.2: Word (.docx) export — same content as the PDF: FR5.6 header
    info block and page footer, disclosures BEFORE the item list, summary
    sections, item table and appendix analysis tables.

    FR7.2: the view is sanitised first (idempotent)."""
    view = sanitise_view(view)
    from docx import Document as DocxDocument

    generated_at = datetime.now(timezone.utc)
    generated_str = generated_at.strftime("%Y-%m-%d %H:%M UTC")
    data_as_of = (view.get("data_as_of") or "unknown")[:10]
    footer_text = (
        f"Generated by SOWKNOW Collection · {generated_str} · data as of {data_as_of}"
    )

    doc = DocxDocument()

    # ── Header: request params summary, timestamps (FR5.6) ───────────────
    doc.add_heading("SOWKNOW Collection Deliverable", level=0)
    doc.add_paragraph(f"Generated {generated_str} · Data as of {data_as_of}")
    doc.add_paragraph(
        f"Deliverable v{view.get('version', 1)} · "
        f"{len(view.get('items') or [])} item(s) · "
        "Links are permission-bound (re-checked at navigation)."
    )
    appendix = view.get("appendix") or {}
    if appendix.get("request_params"):
        doc.add_paragraph(f"Request: {appendix['request_params']}")

    # ── Disclosures BEFORE the item list (FR5.6) ─────────────────────────
    disclosures = view.get("disclosures") or []
    if disclosures:
        doc.add_heading("Disclosures", level=1)
        for disclosure in disclosures:
            doc.add_paragraph(_disclosure_text(disclosure), style="List Bullet")

    # ── Summary ──────────────────────────────────────────────────────────
    if view.get("summary_md"):
        doc.add_heading("Summary", level=1)
        for kind, text in _md_to_blocks(view["summary_md"]):
            if kind == "heading":
                doc.add_heading(text, level=2)
            elif kind == "bullet":
                doc.add_paragraph(text, style="List Bullet")
            else:
                doc.add_paragraph(text)

    # ── Item list ────────────────────────────────────────────────────────
    items = view.get("items") or []
    if items:
        doc.add_heading("Source Items", level=1)
        table = doc.add_table(rows=1, cols=4)
        table.style = "Table Grid"
        for index, header in enumerate(["#", "Title", "Date", "Annotation"]):
            table.rows[0].cells[index].text = header
        for item in items:
            cells = table.add_row().cells
            cells[0].text = str(item.get("rank_position") or "—")
            cells[1].text = (item.get("title") or "untitled")[:60]
            cells[2].text = (item.get("date") or "—")[:10]
            cells[3].text = (item.get("annotation") or "")[:180]

    # ── Appendix: analysis tables (charts stay in the in-app view) ───────
    rendered = appendix.get("analyses_rendered") or []
    if rendered:
        doc.add_heading("Appendix — Computed Analyses", level=1)
        for entry in rendered:
            paragraph = doc.add_paragraph()
            paragraph.add_run(str(entry.get("analysis_type"))).bold = True
            for message in entry.get("messages") or []:
                doc.add_paragraph(str(message), style="List Bullet")
            for table_spec in entry.get("tables") or []:
                columns = table_spec.get("columns") or []
                rows = [
                    [str(row.get(col, "—")) for col in columns]
                    for row in table_spec.get("rows") or []
                ]
                if not rows:
                    continue
                doc.add_paragraph(str(table_spec.get("title") or ""))
                a_table = doc.add_table(rows=1, cols=len(columns))
                a_table.style = "Table Grid"
                for index, column in enumerate(columns):
                    a_table.rows[0].cells[index].text = str(column)
                for row in rows:
                    cells = a_table.add_row().cells
                    for index, value in enumerate(row):
                        cells[index].text = value

    # ── FR5.6 footer info block on every page ────────────────────────────
    doc.sections[0].footer.paragraphs[0].text = footer_text

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# ---------------------------------------------------------------------------
# FR5.5 — deliverable version diff
# ---------------------------------------------------------------------------

# Lines before the first recognised section header.
PREAMBLE_SECTION = "Preamble"

_HEADING_RE = re.compile(r"^#{1,6}\s+(.*?)\s*#*\s*$")

# Section names are matched case-insensitively against the FR4.2.2 set.
_SECTION_NAMES = {s.lower(): s for s in SECTIONS}


def split_summary_sections(summary_md: str) -> dict[str, list[str]]:
    """Split a summary into its FR4.2.2 sections (Overview / Key Findings /
    Trends & Patterns / Notable Anomalies / Supporting Data).

    Content before the first recognised header is reported under
    "Preamble". Unrecognised headings stay inside the current section.
    Returns {section_name: [lines]} in document order.
    """
    sections: dict[str, list[str]] = {}
    current: str | None = None
    for line in (summary_md or "").splitlines():
        heading = _HEADING_RE.match(line.strip())
        name = _SECTION_NAMES.get(heading.group(1).lower()) if heading else None
        if name is not None:
            current = name
            sections.setdefault(current, [])
            continue
        if current is None:
            current = PREAMBLE_SECTION
            sections.setdefault(current, [])
        sections[current].append(line)
    return sections


def diff_disclosures(
    disclosures_from: list[dict[str, Any]] | None,
    disclosures_to: list[dict[str, Any]] | None,
) -> dict[str, Any]:
    """Compare two disclosure lists keyed on their ``type``: added types,
    removed types, and types present in both whose payload changed."""
    def _by_type(disclosures):
        result: dict[str, dict[str, Any]] = {}
        for disclosure in disclosures or []:
            if isinstance(disclosure, dict):
                result[str(disclosure.get("type") or "unknown")] = disclosure
        return result

    old = _by_type(disclosures_from)
    new = _by_type(disclosures_to)
    return {
        "added": [new[t] for t in new if t not in old],
        "removed": [old[t] for t in old if t not in new],
        "changed": [new[t] for t in new if t in old and new[t] != old[t]],
    }


def diff_deliverables(deliverable_from: Any, deliverable_to: Any) -> dict[str, Any]:
    """FR5.5: per-section unified diff of two deliverable versions.

    Sections missing on one side are reported as added/removed; identical
    sections as unchanged (with an empty diff).
    """
    import difflib

    sections_from = split_summary_sections(
        getattr(deliverable_from, "summary_md", None) or ""
    )
    sections_to = split_summary_sections(
        getattr(deliverable_to, "summary_md", None) or ""
    )

    ordered_names = [PREAMBLE_SECTION, *SECTIONS]
    extras = [
        name for name in (*sections_from, *sections_to)
        if name not in ordered_names
    ]
    section_diffs: list[dict[str, Any]] = []
    for name in [*ordered_names, *dict.fromkeys(extras)]:
        old = sections_from.get(name)
        new = sections_to.get(name)
        if old is None and new is None:
            continue
        if old is None:
            status, diff = "added", []
        elif new is None:
            status, diff = "removed", []
        elif old == new:
            status, diff = "unchanged", []
        else:
            status = "changed"
            diff = list(difflib.unified_diff(
                old, new,
                fromfile=f"v{getattr(deliverable_from, 'version', '?')}",
                tofile=f"v{getattr(deliverable_to, 'version', '?')}",
                lineterm="",
            ))
        section_diffs.append({"section": name, "status": status, "diff": diff})

    return {
        "from_version": getattr(deliverable_from, "version", None),
        "to_version": getattr(deliverable_to, "version", None),
        "sections": section_diffs,
        "disclosures": diff_disclosures(
            getattr(deliverable_from, "disclosures", None),
            getattr(deliverable_to, "disclosures", None),
        ),
    }
