#!/bin/bash
###############################################################################
# verify_tree.sh — compile/sanity gate for the sowknow4 tree.
#
# Born from the 2026-09-05 Ollama-removal incident: a pattern-based `sed`
# deletion broke JSX in 2 files, Python syntax in 4, a runtime import in 1,
# and orphaned a dataclass field — ALL of it committed without any check,
# and ALL of it catchable by these gates in seconds.
#
# Usage:
#   scripts/verify_tree.sh              # check files STAGED for commit (default)
#   scripts/verify_tree.sh --all        # check the whole tree (pre-deploy)
#   scripts/verify_tree.sh --staged --imports   # + backend import smoke
#
# Gates:
#   1. Python syntax     — ast/py_compile per file (catches sed-amputated code)
#   2. TypeScript        — tsc --noEmit over frontend (catches broken JSX)
#   3. JSON validity     — messages/*.json etc.
#   4. (--imports)       — backend `import app.main` via backend/venv
#
# Exit 0 = clean, exit 1 = at least one failure (all failures listed).
###############################################################################
set -uo pipefail

cd "$(dirname "$0")/.."

MODE="staged"
RUN_IMPORTS=0
for arg in "$@"; do
    case "$arg" in
        --staged)  MODE="staged" ;;
        --all)     MODE="all" ;;
        --imports) RUN_IMPORTS=1 ;;
        *) echo "unknown arg: $arg"; exit 2 ;;
    esac
done

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
FAILURES=()

# Collect candidate files (NUL-delimited — paths contain [brackets]/spaces).
if [ "$MODE" = "staged" ]; then
    mapfile -d '' FILES < <(git diff --cached --name-only --diff-filter=ACMR -z)
else
    mapfile -d '' FILES < <(
        { find backend/app monitoring -name '*.py' -not -path '*__pycache__*';
          find frontend/app frontend/lib frontend/components frontend/hooks frontend/services frontend/types frontend/utils -name '*.ts' -o -name '*.tsx' 2>/dev/null;
          find frontend/app/messages -name '*.json'; } | sort -u | tr '\n' '\0'
    )
fi

# Generated artifacts — never gate on them (they are regenerated by the hook).
is_generated() {
    case "$1" in
        scripts/structural_audit/*|.context/*|*/venv/*|*/node_modules/*) return 0 ;;
        *) return 1 ;;
    esac
}

PY_FILES=(); TS_FILES=(); JSON_FILES=()
for f in "${FILES[@]}"; do
    is_generated "$f" && continue
    [ -f "$f" ] || continue
    case "$f" in
        *.py)  PY_FILES+=("$f") ;;
        *.ts|*.tsx) TS_FILES+=("$f") ;;
        *.json) JSON_FILES+=("$f") ;;
    esac
done

echo "verify_tree: mode=$MODE  py=${#PY_FILES[@]} ts=${#TS_FILES[@]} json=${#JSON_FILES[@]}"

# ── Gate 1: Python syntax ────────────────────────────────────────────────────
for f in "${PY_FILES[@]:-}"; do
    [ -n "$f" ] || continue
    if ! PYTHONDONTWRITEBYTECODE=1 python3 -m py_compile "$f" 2>/tmp/verify_tree_py.err; then
        FAILURES+=("PY SYNTAX: $f $(head -2 /tmp/verify_tree_py.err | tr '\n' ' ')")
    fi
done

# ── Gate 2: TypeScript (tsc --noEmit is full-tree: the only reliable way
#    to catch a broken JSX block, wherever it is) ─────────────────────────────
if [ "${#TS_FILES[@]}" -gt 0 ]; then
    if [ -x frontend/node_modules/.bin/tsc ]; then
        TSC_OUT=$( (cd frontend && ./node_modules/.bin/tsc --noEmit) 2>&1 )
        TSC_RC=$?
        if [ "$TSC_RC" -ne 0 ]; then
            TSC_SUMMARY=$(echo "$TSC_OUT" | head -15)
            FAILURES+=("TYPESCRIPT: tsc --noEmit failed:
$TSC_SUMMARY")
        fi
    else
        echo -e "${YELLOW}verify_tree: frontend/node_modules missing — skipping tsc${NC}"
    fi
fi

# ── Gate 3: JSON validity ────────────────────────────────────────────────────
for f in "${JSON_FILES[@]:-}"; do
    [ -n "$f" ] || continue
    if ! python3 -m json.tool "$f" > /dev/null 2>&1; then
        FAILURES+=("JSON INVALID: $f")
    fi
done

# ── Gate 4 (opt-in): backend import smoke ───────────────────────────────────
if [ "$RUN_IMPORTS" -eq 1 ]; then
    if [ -x backend/venv/bin/python ]; then
        if ! (cd backend && ./venv/bin/python -c "import app.main" >/dev/null 2>/tmp/verify_tree_import.err); then
            FAILURES+=("BACKEND IMPORT: app.main failed: $(head -3 /tmp/verify_tree_import.err | tr '\n' ' ')")
        fi
    else
        echo -e "${YELLOW}verify_tree: backend/venv missing — import smoke skipped${NC}"
    fi
fi

# ── Verdict ──────────────────────────────────────────────────────────────────
if [ "${#FAILURES[@]}" -gt 0 ]; then
    echo -e "${RED}✗ verify_tree: ${#FAILURES[@]} failure(s):${NC}"
    for msg in "${FAILURES[@]}"; do echo -e "${RED}  - $msg${NC}"; done
    echo -e "${YELLOW}Fix the files above. Pattern-based rewrites (sed/grep -l | xargs rm)"
    echo -e "must always be followed by: scripts/verify_tree.sh --all${NC}"
    exit 1
fi

echo -e "${GREEN}✓ verify_tree: clean${NC}"
exit 0
